apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: demodb
  namespace: project2
spec:
  redisEnterpriseCluster:
    name: rec2
  memorySize: 1GB
  tlsMode: enabled
